-- Wave 7B Track B — HouseholdAgent daily brief table.
--
-- Distinct from the existing `mise_daily_briefs` (which is the LLM brief loop
-- in src/mise-graph/daily-brief.ts). This table is the structured cache the
-- HouseholdAgent DO writes from its `morningCheckin` alarm and reads via
-- /daily-brief. Each row captures the inputs (weather + calendar + plan
-- health + suggestions) and the brief id that the daily-brief loop emitted.
--
-- Idempotent: safe to apply on every deploy.

CREATE TABLE IF NOT EXISTS mise_household_agent_briefs (
    id TEXT PRIMARY KEY,                    -- ulid-ish, generated by the agent
    household_id TEXT NOT NULL,
    for_date TEXT NOT NULL,                 -- YYYY-MM-DD this brief is FOR
    weather_summary_json TEXT,              -- forecast + cooking hints (subset)
    calendar_windows_json TEXT,             -- next-3-days CalendarWindow[]
    plan_health_json TEXT,                  -- per-plan grievance counts + missed prep flags
    suggestions_json TEXT,                  -- list of suggested actions
    brief_id TEXT,                          -- pointer to mise_daily_briefs.brief_id when populated
    created_at_ms INTEGER NOT NULL,
    updated_at_ms INTEGER NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_household_agent_briefs_unique
    ON mise_household_agent_briefs(household_id, for_date);

CREATE INDEX IF NOT EXISTS idx_household_agent_briefs_recent
    ON mise_household_agent_briefs(household_id, created_at_ms DESC);
