// Mise cuisine fusions + flavor vibes seed.
//
// REAL-WORLD FUSIONS
// ------------------
// Each row pairs two cuisines (alphabetized in cuisine_a/cuisine_b) with an
// affinity in [0, 1] and an is_canon flag. is_canon = true means the pair
// has, over time, fused into its own recognized cuisine — Tex-Mex, Nikkei
// Japanese-Peruvian, Chifa Chinese-Peruvian, Indian-Chinese (Indo-Chinese),
// Anglo-Indian, Vietnamese-French (banh mi heritage), Creole/Cajun, modern
// Californian, Tex-Mex. Non-canon fusions still happen on real menus but
// haven't crystallized into a named cuisine.
//
// Affinity is a chef judgment, not a measurement: 0.95+ for textbook canons,
// 0.85-0.9 for "modern menu staples," 0.5-0.7 for "happens but be careful,"
// < 0.5 reserved for genuine clashes captured in DIVERGENCES below.
//
// CROSS-CUISINE VIBES
// -------------------
// A "vibe" is a named flavor gesture that travels across cuisines:
// "gochujang-aioli", "miso-butter on anything", "preserved-lemon-everything,"
// "chili-crisp-on-everything," "harissa-honey." Each vibe lists its
// signature ingredients, components (sub-recipes that show up across many
// dishes), and example dishes. The composer can quote these when pushing a
// menu toward a flavor mood without being locked to a single cuisine.

export interface CuisineFusionSeed {
	id: string;
	cuisine_a: string;
	cuisine_b: string;
	fusion_label: string | null;
	affinity: number;
	is_canon: boolean;
	example_dishes: string[];
	example_components: string[];
	notes: string | null;
}

export interface FlavorVibeSeed {
	id: string;
	label: string;
	description: string | null;
	cross_cuisine_marker: string | null;
	signature_ingredients: string[];
	example_dishes: string[];
	example_components: string[];
	vibe_kind: "sauce" | "spice" | "method" | "produce" | "umami" | "general";
}

// ---------------------------------------------------------------------------
// Cuisine fusions
// ---------------------------------------------------------------------------

export const cuisineFusionsSeed: CuisineFusionSeed[] = [
	{
		id: "fusion_korean_mexican",
		cuisine_a: "korean",
		cuisine_b: "mexican",
		fusion_label: "Korean-Mexican",
		affinity: 0.9,
		is_canon: true,
		example_dishes: [
			"kalbi short-rib tacos",
			"kimchi quesadilla",
			"bulgogi torta",
			"gochujang carnitas",
			"Korean BBQ burrito",
			"kimchi fried-rice quesadilla",
		],
		example_components: [
			"gochujang aioli",
			"kimchi salsa",
			"sesame-cilantro slaw",
			"bulgogi marinade",
			"gochujang-lime crema",
		],
		notes: "LA-born fusion (Roy Choi / Kogi BBQ ~2008). Korean tacos are now a stable American genre.",
	},
	{
		id: "fusion_chinese_indian",
		cuisine_a: "chinese",
		cuisine_b: "indian",
		fusion_label: "Indian-Chinese (Indo-Chinese)",
		affinity: 0.95,
		is_canon: true,
		example_dishes: [
			"gobi manchurian",
			"hakka noodles",
			"chili paneer",
			"schezwan dosa",
			"chicken 65",
			"manchow soup",
			"chili chicken",
		],
		example_components: [
			"schezwan sauce (Indian style)",
			"manchurian gravy",
			"green-chili soy",
			"ginger-garlic-chili paste",
		],
		notes: "Hakka Chinese in Kolkata since the 1950s; now its own pan-India genre with green-chili + soy + ginger as backbone.",
	},
	{
		id: "fusion_chinese_peruvian",
		cuisine_a: "chinese",
		cuisine_b: "peruvian",
		fusion_label: "Chifa",
		affinity: 0.95,
		is_canon: true,
		example_dishes: [
			"lomo saltado",
			"arroz chaufa",
			"aji-amarillo wonton",
			"tallarin saltado",
			"sopa wonton",
		],
		example_components: [
			"sillao (Peruvian soy)",
			"aji-amarillo paste",
			"wok-charred sauce base",
		],
		notes: "Chinese-Peruvian, ~1850s Cantonese laborers. Stir-fry + aji + soy is the spine.",
	},
	{
		id: "fusion_japanese_peruvian",
		cuisine_a: "japanese",
		cuisine_b: "peruvian",
		fusion_label: "Nikkei",
		affinity: 0.95,
		is_canon: true,
		example_dishes: [
			"tiradito",
			"nikkei ceviche",
			"miso anticucho",
			"tuna tataki with leche de tigre",
			"sushi roll with rocoto",
		],
		example_components: [
			"yuzu-leche de tigre",
			"miso-aji glaze",
			"soy-rocoto dressing",
		],
		notes: "Japanese-Peruvian heritage, 20th c. Nobu-era global awareness. Raw fish + aji + citrus.",
	},
	{
		id: "fusion_caribbean_chinese",
		cuisine_a: "caribbean",
		cuisine_b: "chinese",
		fusion_label: "Chinese-Caribbean",
		affinity: 0.85,
		is_canon: false,
		example_dishes: [
			"Chinese-Jamaican curry chicken",
			"char-siu jerk pork",
			"oxtail fried rice",
			"sweet-and-sour saltfish",
		],
		example_components: [
			"jerk-spiced char siu glaze",
			"scotch-bonnet soy",
		],
		notes: "Especially strong in Jamaica and Trinidad — Chinese-Caribbean diasporic cooking.",
	},
	{
		id: "fusion_french_vietnamese",
		cuisine_a: "french",
		cuisine_b: "vietnamese",
		fusion_label: "Vietnamese-French (banh mi heritage)",
		affinity: 0.95,
		is_canon: true,
		example_dishes: [
			"banh mi",
			"pho-style pot-au-feu",
			"cafe sua da (coffee + condensed milk)",
			"pâté chaud",
			"bo kho (Vietnamese beef stew with star anise)",
		],
		example_components: [
			"pâté on crusty baguette",
			"pickled daikon-carrot (do chua)",
			"coffee-condensed-milk",
			"five-spice braising stock",
		],
		notes: "French colonial era. Baguette, pâté, coffee, and braising technique fused with Vietnamese herb + fish-sauce backbone.",
	},
	{
		id: "fusion_thai_western",
		cuisine_a: "thai",
		cuisine_b: "western",
		fusion_label: "Thai-Western (modern)",
		affinity: 0.7,
		is_canon: false,
		example_dishes: [
			"tom-yum risotto",
			"makrut lime butter scallops",
			"green-curry mussels",
			"thai-basil pesto pasta",
		],
		example_components: [
			"makrut lime butter",
			"thai-basil pesto",
			"tom-yum cream",
		],
		notes: "Modern restaurant fusion — works when the herb backbone (lemongrass, makrut, thai basil) leads.",
	},
	{
		id: "fusion_korean_western",
		cuisine_a: "korean",
		cuisine_b: "western",
		fusion_label: "Korean-Western (modern)",
		affinity: 0.85,
		is_canon: false,
		example_dishes: [
			"gochujang-glazed brussels sprouts",
			"kimchi grilled cheese",
			"gochujang aioli on smashburger",
			"korean fried chicken sliders",
			"gochujang cacio e pepe",
		],
		example_components: [
			"gochujang aioli",
			"gochujang-honey glaze",
			"kimchi mayo",
			"sesame compound butter",
		],
		notes: "Stable in modern American restaurants — gochujang is the new sriracha.",
	},
	{
		id: "fusion_italian_levantine",
		cuisine_a: "italian",
		cuisine_b: "levantine",
		fusion_label: "Italian-Levantine",
		affinity: 0.85,
		is_canon: false,
		example_dishes: [
			"hummus pasta",
			"sumac pizza",
			"labneh ravioli",
			"za'atar focaccia",
			"tahini cacio e pepe",
		],
		example_components: [
			"za'atar olive oil",
			"sumac-onion topping",
			"labneh ricotta sub",
			"tahini-parmesan sauce",
		],
		notes: "Mediterranean shared spine — both lean olive-oil + grain + bright acid + herb. Easy bridge.",
	},
	{
		id: "fusion_italian_mexican",
		cuisine_a: "italian",
		cuisine_b: "mexican",
		fusion_label: "Italian-Mexican",
		affinity: 0.55,
		is_canon: false,
		example_dishes: [
			"chorizo pasta",
			"pasta with pico de gallo",
			"calabrian-chili tacos",
			"poblano-cream lasagna",
		],
		example_components: [
			"calabrian chili-lime butter",
			"chorizo ragu",
		],
		notes: "Works narrowly — chorizo + tomato sauce + pasta is solid; broader fusion gets muddy.",
	},
	{
		id: "fusion_italian_japanese",
		cuisine_a: "italian",
		cuisine_b: "japanese",
		fusion_label: "Italian-Japanese",
		affinity: 0.5,
		is_canon: false,
		example_dishes: [
			"miso butter pasta (divisive but real)",
			"uni risotto",
			"matcha tiramisu",
			"shoyu carbonara",
			"yuzu-pepper agnolotti",
		],
		example_components: [
			"miso butter",
			"yuzu-kosho cream",
			"shoyu reduction",
			"uni cream sauce",
		],
		notes: "Polarizing in tradition; reliable in modern restaurants when the umami + butter axis leads.",
	},
	{
		id: "fusion_indian_italian",
		cuisine_a: "indian",
		cuisine_b: "italian",
		fusion_label: "Indian-Italian",
		affinity: 0.5,
		is_canon: false,
		example_dishes: [
			"tikka masala pasta",
			"butter-chicken stuffed cannoli (it exists)",
			"curry-leaf pesto pasta",
			"saag paneer ravioli",
		],
		example_components: [
			"curry-leaf pesto",
			"butter-chicken cream",
			"garam-masala olive oil",
		],
		notes: "Genuinely tricky — works when one cuisine is the spine and the other contributes one or two specific notes.",
	},
	{
		id: "fusion_french_japanese",
		cuisine_a: "french",
		cuisine_b: "japanese",
		fusion_label: "French-Japanese",
		affinity: 0.85,
		is_canon: false,
		example_dishes: [
			"yuzu hollandaise",
			"miso-butter sole meunière",
			"dashi consommé",
			"matcha financier",
			"foie gras with daikon and yuzu",
		],
		example_components: [
			"yuzu hollandaise",
			"miso compound butter",
			"dashi cream",
			"sake beurre blanc",
		],
		notes: "Tokyo French / modern Paris bistros for decades. Delicate but proven — both cuisines value technique + restraint.",
	},
	{
		id: "fusion_french_moroccan",
		cuisine_a: "french",
		cuisine_b: "moroccan",
		fusion_label: "French-Moroccan",
		affinity: 0.85,
		is_canon: false,
		example_dishes: [
			"tagine de boeuf with merguez",
			"harissa-roasted lamb",
			"preserved-lemon roast chicken",
			"couscous royale",
			"ras-el-hanout-spiced cassoulet",
		],
		example_components: [
			"harissa beurre blanc",
			"preserved-lemon vinaigrette",
			"ras el hanout butter",
		],
		notes: "Colonial-era cross-pollination; classic Paris bistro repertoire.",
	},
	{
		id: "fusion_levantine_mediterranean",
		cuisine_a: "levantine",
		cuisine_b: "mediterranean",
		fusion_label: "Levantine-Mediterranean",
		affinity: 0.95,
		is_canon: true,
		example_dishes: [
			"hummus",
			"tabbouleh",
			"herbed olive-oil bread",
			"fattoush",
			"baba ghanoush",
			"shakshuka",
		],
		example_components: [
			"za'atar olive oil",
			"tahini-lemon dressing",
			"herbed labneh",
		],
		notes: "Broad regional overlap — they share olive oil, citrus, herbs, grains, sesame.",
	},
	{
		id: "fusion_mediterranean_north_african",
		cuisine_a: "mediterranean",
		cuisine_b: "north_african",
		fusion_label: "Mediterranean-North African",
		affinity: 0.9,
		is_canon: false,
		example_dishes: [
			"shakshuka",
			"harissa pasta",
			"preserved-lemon vinaigrette",
			"merguez flatbread",
			"orange-fennel-olive salad",
		],
		example_components: [
			"harissa-honey glaze",
			"preserved-lemon dressing",
			"ras-el-hanout oil",
		],
		notes: "Andalusian + Maghrebi crossroads — chili, citrus, cumin, olive oil are shared.",
	},
	{
		id: "fusion_levantine_mexican",
		cuisine_a: "levantine",
		cuisine_b: "mexican",
		fusion_label: "Levantine-Mexican (Lebanese-Mexican lineage)",
		affinity: 0.7,
		is_canon: false,
		example_dishes: [
			"tacos al pastor (Lebanese-Mexican lineage)",
			"chipotle hummus",
			"harissa salsa",
			"shawarma tacos",
		],
		example_components: [
			"chipotle tahini",
			"harissa-lime crema",
			"sumac-cilantro-onion",
		],
		notes: "Tacos al pastor descend from Lebanese shawarma in Puebla — vertical-spit pork is direct lineage.",
	},
	{
		id: "fusion_mexican_texan",
		cuisine_a: "mexican",
		cuisine_b: "texan",
		fusion_label: "Tex-Mex",
		affinity: 1.0,
		is_canon: true,
		example_dishes: [
			"chili con carne",
			"fajitas",
			"queso (chile con queso)",
			"breakfast tacos",
			"chimichanga",
			"nachos supreme",
		],
		example_components: [
			"yellow cheese sauce",
			"cumin-heavy chili",
			"flour tortilla (Tex-Mex thicker)",
			"refried beans",
		],
		notes: "Recognized cuisine since at least the 1970s; cumin + yellow cheese + flour tortilla are the giveaways.",
	},
	{
		id: "fusion_californian",
		cuisine_a: "californian",
		cuisine_b: "californian",
		fusion_label: "Californian",
		affinity: 1.0,
		is_canon: true,
		example_dishes: [
			"Chez Panisse-style market salad",
			"fish tacos",
			"sushi burrito",
			"kale Caesar",
			"avocado toast",
			"green-goddess bowl",
		],
		example_components: [
			"green goddess",
			"market vinaigrette",
			"avocado crema",
		],
		notes: "Californian is itself a cuisine of fusion: Asian + Mexican + Mediterranean filtered through farm-to-table seasonality.",
	},
	{
		id: "fusion_african_caribbean",
		cuisine_a: "african",
		cuisine_b: "caribbean",
		fusion_label: "African-Caribbean",
		affinity: 0.85,
		is_canon: false,
		example_dishes: [
			"jerk chicken",
			"callaloo",
			"oxtail stew",
			"ackee and saltfish",
			"jollof rice",
		],
		example_components: [
			"jerk marinade",
			"scotch-bonnet pepper sauce",
			"green seasoning",
		],
		notes: "Direct West-African heritage in Caribbean cooking — yams, okra, peppers, slow-braised stews.",
	},
	{
		id: "fusion_middle_eastern_southeast_asian",
		cuisine_a: "middle_eastern",
		cuisine_b: "southeast_asian",
		fusion_label: "Middle Eastern-Southeast Asian",
		affinity: 0.5,
		is_canon: false,
		example_dishes: [
			"sumac-lime som tam",
			"harissa rendang",
			"za'atar-spiced satay",
		],
		example_components: [
			"sumac-lime dressing",
			"harissa-coconut sauce",
		],
		notes: "Rare on menus but works when chili + citrus + herb + ferment line up.",
	},
	{
		id: "fusion_ethiopian_levantine",
		cuisine_a: "ethiopian",
		cuisine_b: "levantine",
		fusion_label: "Ethiopian-Levantine",
		affinity: 0.7,
		is_canon: false,
		example_dishes: [
			"misir-with-pita",
			"berbere-spiced hummus",
			"injera-style flatbread with za'atar",
		],
		example_components: [
			"berbere oil",
			"berbere-tahini dressing",
		],
		notes: "Both cuisines anchor on legumes + flatbread + spice; berbere + tahini is a real pairing.",
	},
	{
		id: "fusion_mexican_spanish",
		cuisine_a: "mexican",
		cuisine_b: "spanish",
		fusion_label: "Spanish-Mexican",
		affinity: 0.85,
		is_canon: false,
		example_dishes: [
			"paella-style rice",
			"churros",
			"tres leches cake",
			"chorizo-style tacos",
			"flan",
		],
		example_components: [
			"smoked paprika oil",
			"chorizo crumble",
			"saffron rice base",
		],
		notes: "Foundational lineage — Mexican cuisine descends in part from Spanish colonial pantry.",
	},
	{
		id: "fusion_moroccan_spanish",
		cuisine_a: "moroccan",
		cuisine_b: "spanish",
		fusion_label: "Spanish-Moroccan (al-Andalus heritage)",
		affinity: 0.9,
		is_canon: false,
		example_dishes: [
			"ras-el-hanout paella",
			"tortilla española with merguez",
			"saffron-cumin lamb",
			"orange-blossom flan",
		],
		example_components: [
			"ras-el-hanout oil",
			"preserved-lemon aioli",
			"orange-blossom syrup",
		],
		notes: "Al-Andalus / Moorish Iberia — saffron, cumin, almond, citrus all came from this exchange.",
	},
	{
		id: "fusion_african_french_spanish_creole",
		cuisine_a: "creole",
		cuisine_b: "creole",
		fusion_label: "Creole/Cajun (French-African-Spanish-Caribbean)",
		affinity: 0.95,
		is_canon: true,
		example_dishes: [
			"gumbo",
			"jambalaya",
			"étouffée",
			"shrimp creole",
			"red beans and rice",
			"po'boy",
		],
		example_components: [
			"holy trinity (onion-celery-bell pepper)",
			"dark roux",
			"creole seasoning",
			"andouille",
		],
		notes: "New Orleans melting pot — French (roux), African (okra, file), Spanish (rice), Caribbean (chili), Choctaw (file powder).",
	},
	{
		id: "fusion_african_southern_us",
		cuisine_a: "african",
		cuisine_b: "southern_us",
		fusion_label: "Southern (Soul) — African-Southern US",
		affinity: 0.95,
		is_canon: true,
		example_dishes: [
			"hoppin' john",
			"collard greens",
			"oxtail",
			"fried green tomatoes",
			"chitterlings",
			"black-eyed peas",
			"smothered chicken",
		],
		example_components: [
			"pot likker",
			"smoked-pork seasoning",
			"sorghum glaze",
		],
		notes: "African-American soul cuisine — direct descendant of West African foodways with Southern US adaptations.",
	},
	{
		id: "fusion_chinese_southeast_asian",
		cuisine_a: "chinese",
		cuisine_b: "southeast_asian",
		fusion_label: "Chinese-Southeast Asian",
		affinity: 0.85,
		is_canon: false,
		example_dishes: [
			"hokkien mee",
			"char kway teow",
			"laksa",
			"bak kut teh",
			"hainan chicken rice",
		],
		example_components: [
			"sambal-oyster sauce",
			"chili-soy-lime",
			"fried-shallot oil",
		],
		notes: "Diaspora-driven — Hokkien + Cantonese + Teochew migrants seeded huge swaths of SE Asian street food.",
	},
	{
		id: "fusion_chinese_thai",
		cuisine_a: "chinese",
		cuisine_b: "thai",
		fusion_label: "Thai-Chinese",
		affinity: 0.9,
		is_canon: true,
		example_dishes: [
			"pad see ew",
			"kuay tiao (boat noodles)",
			"kana mu krob (Thai-Chinese crispy pork + greens)",
			"khao mun gai",
			"rad na",
		],
		example_components: [
			"oyster-sauce-soy stir base",
			"Thai-Chinese chili vinegar",
		],
		notes: "Thai-Chinese is its own internal cuisine in Thailand — wok-charred noodles + soy + sugar + chili + Thai herbs.",
	},
	{
		id: "fusion_hawaiian_japanese",
		cuisine_a: "hawaiian",
		cuisine_b: "japanese",
		fusion_label: "Hawaiian-Japanese (local)",
		affinity: 0.9,
		is_canon: true,
		example_dishes: [
			"poke",
			"spam musubi",
			"loco moco",
			"garlic shrimp plate",
			"saimin",
			"chicken katsu plate lunch",
		],
		example_components: [
			"shoyu-poke sauce",
			"furikake butter",
			"musubi nori wrap",
		],
		notes: "Plantation-era Japanese immigration to Hawaii — Hawaiian local food is heavily Japanese-inflected.",
	},
	{
		id: "fusion_japanese_korean",
		cuisine_a: "japanese",
		cuisine_b: "korean",
		fusion_label: "Japanese-Korean (izakaya overlap)",
		affinity: 0.85,
		is_canon: false,
		example_dishes: [
			"kimchi onigiri",
			"Korean curry rice",
			"bibimbap with shoyu egg",
			"yakitori with gochujang glaze",
		],
		example_components: [
			"gochujang-shoyu glaze",
			"sesame-kimchi seasoning",
		],
		notes: "Decades of cross-pollination via izakaya, curry rice, and shared umami spine (soy + sesame + ferment).",
	},
	{
		id: "fusion_cajun_soul",
		cuisine_a: "cajun",
		cuisine_b: "soul",
		fusion_label: "Soul-Cajun",
		affinity: 0.9,
		is_canon: false,
		example_dishes: [
			"gumbo with collards",
			"blackened catfish",
			"jambalaya with smoked turkey",
			"red beans with andouille and ham hock",
		],
		example_components: [
			"blackening spice",
			"smoked-pork seasoning",
			"holy trinity",
		],
		notes: "Geographic + cultural overlap in the Gulf South; both cuisines lean smoked pork + greens + spiced rice.",
	},
	{
		id: "fusion_japanese_portuguese",
		cuisine_a: "japanese",
		cuisine_b: "portuguese",
		fusion_label: "Japanese-Portuguese",
		affinity: 0.85,
		is_canon: true,
		example_dishes: [
			"tempura (Portuguese-derived)",
			"castella (kasutera) cake",
			"konpeito sugar candy",
			"Portuguese-style miso bread",
		],
		example_components: [
			"tempura batter",
			"miso bread crumb",
		],
		notes: "16th-century Portuguese missionaries introduced batter-frying (peixinhos da horta → tempura), sugar refinement, and bread.",
	},
	{
		id: "fusion_british_indian",
		cuisine_a: "british",
		cuisine_b: "indian",
		fusion_label: "British-Indian (Anglo-Indian)",
		affinity: 0.9,
		is_canon: true,
		example_dishes: [
			"chicken tikka masala",
			"jalfrezi",
			"kedgeree",
			"mulligatawny soup",
			"vindaloo (UK-style)",
			"chicken korma (UK-style)",
		],
		example_components: [
			"tikka-masala cream sauce",
			"kedgeree spice mix",
			"curry powder (Anglo blend)",
		],
		notes: "Colonial-era and post-WWII UK migration. Tikka masala is the canonical Anglo-Indian invention; curry-house genre is its own cuisine.",
	},
	{
		id: "fusion_filipino_spanish",
		cuisine_a: "filipino",
		cuisine_b: "spanish",
		fusion_label: "Filipino-Spanish",
		affinity: 0.9,
		is_canon: true,
		example_dishes: [
			"adobo",
			"caldereta",
			"menudo (Filipino, not Mexican)",
			"leche flan",
			"pan de sal",
			"morcon",
		],
		example_components: [
			"vinegar-soy adobo base",
			"tomato-paprika sauce",
			"annatto oil",
		],
		notes: "300+ years of Spanish colonization — soy + vinegar Filipino spine + Spanish tomato-pepper-saffron technique.",
	},
	{
		id: "fusion_caribbean_indian",
		cuisine_a: "caribbean",
		cuisine_b: "indian",
		fusion_label: "Indo-Caribbean",
		affinity: 0.9,
		is_canon: true,
		example_dishes: [
			"trinidad doubles",
			"roti with curry goat",
			"chana (curried chickpea)",
			"pholourie",
			"aloo pie",
		],
		example_components: [
			"trinidad curry powder",
			"green seasoning",
			"tamarind-chili chutney",
		],
		notes: "19th c. Indian indentured labor in Trinidad/Guyana — own genre with chili + cumin + scotch bonnet + roti.",
	},
];

// Cuisine-divergences: pairs that rarely land well. Stored as fusions with
// affinity < 0.4 and is_canon false, so the loader can return them when the
// composer asks "what should I avoid mashing together?"
export const cuisineDivergencesSeed: CuisineFusionSeed[] = [
	{
		id: "divergence_japanese_indian",
		cuisine_a: "indian",
		cuisine_b: "japanese",
		fusion_label: null,
		affinity: 0.3,
		is_canon: false,
		example_dishes: [],
		example_components: [],
		notes: "DIVERGENCE: heavy garam-masala + dashi/miso usually clash — fermented umami fights with toasted-spice depth. Japanese curry rice exists but is mild Anglo-derived, not direct Indian.",
	},
	{
		id: "divergence_french_thai",
		cuisine_a: "french",
		cuisine_b: "thai",
		fusion_label: null,
		affinity: 0.35,
		is_canon: false,
		example_dishes: [],
		example_components: [],
		notes: "DIVERGENCE: French butter + cream sauces tend to mute Thai chili-fish-sauce-lime brightness. Works only when one cuisine fully steps back.",
	},
	{
		id: "divergence_korean_italian",
		cuisine_a: "italian",
		cuisine_b: "korean",
		fusion_label: null,
		affinity: 0.35,
		is_canon: false,
		example_dishes: [],
		example_components: [],
		notes: "DIVERGENCE: gochujang + tomato + parmesan is a triple-umami pile-up. Gochujang cacio e pepe sometimes works, but the broader pairing is risky.",
	},
	{
		id: "divergence_mexican_japanese",
		cuisine_a: "japanese",
		cuisine_b: "mexican",
		fusion_label: null,
		affinity: 0.4,
		is_canon: false,
		example_dishes: [
			"sushi burrito (works as gimmick, not as cuisine)",
		],
		example_components: [],
		notes: "DIVERGENCE: dashi/miso/soy backbone vs cumin/chili/lime/cilantro. Sushi-burrito form survives; broader fusion rarely lands.",
	},
	{
		id: "divergence_indian_french_classique",
		cuisine_a: "french",
		cuisine_b: "indian",
		fusion_label: null,
		affinity: 0.4,
		is_canon: false,
		example_dishes: [],
		example_components: [],
		notes: "DIVERGENCE: classical French (beurre blanc, demi-glace) vs heavy garam masala — butter mutes spice complexity. Pondicherry French-Indian exists but is light French + Tamil, not classique.",
	},
	{
		id: "divergence_chinese_levantine",
		cuisine_a: "chinese",
		cuisine_b: "levantine",
		fusion_label: null,
		affinity: 0.35,
		is_canon: false,
		example_dishes: [],
		example_components: [],
		notes: "DIVERGENCE: soy + ginger + sesame oil vs tahini + lemon + sumac — both cuisines lean sesame, but the surrounding spice grammar collides.",
	},
	{
		id: "divergence_german_mexican",
		cuisine_a: "german",
		cuisine_b: "mexican",
		fusion_label: null,
		affinity: 0.3,
		is_canon: false,
		example_dishes: [],
		example_components: [],
		notes: "DIVERGENCE: caraway/dill/sour cream/pork vs chili/lime/cilantro/masa — ingredient overlap is near zero outside pickled cabbage.",
	},
];

// ---------------------------------------------------------------------------
// Flavor vibes (cross-cuisine flavor moods)
// ---------------------------------------------------------------------------

export const flavorVibesSeed: FlavorVibeSeed[] = [
	{
		id: "vibe_gochujang_aioli",
		label: "gochujang-aioli",
		description: "Korean fermented chili paste whipped into mayo — sweet, savory, fiery, umami. Lives on burgers, fried chicken, fries, tacos.",
		cross_cuisine_marker: "Korean-Western fusion sauces",
		signature_ingredients: ["gochujang", "mayo", "sesame oil", "rice vinegar", "garlic"],
		example_components: ["gochujang aioli", "spicy korean mayo", "kimchi mayo", "gochujang-honey aioli"],
		example_dishes: [
			"Korean smashburger",
			"fried chicken sandwich with gochujang aioli",
			"shrimp tacos with gochujang aioli",
			"crispy Brussels with gochujang mayo",
		],
		vibe_kind: "sauce",
	},
	{
		id: "vibe_miso_butter",
		label: "miso-butter",
		description: "White or red miso whisked into soft butter — instant umami compound that goes on anything seared, roasted, or grilled.",
		cross_cuisine_marker: "Japanese-Western",
		signature_ingredients: ["miso (white or red)", "butter", "mirin", "garlic"],
		example_components: ["miso butter", "miso compound butter", "miso-butter pan sauce"],
		example_dishes: [
			"miso-butter pasta",
			"miso-butter scallops",
			"miso-butter mushroom toast",
			"miso-butter corn on the cob",
			"miso-butter roasted carrots",
		],
		vibe_kind: "sauce",
	},
	{
		id: "vibe_preserved_lemon_everything",
		label: "preserved-lemon-everything",
		description: "Salt-cured Meyer or Eureka lemons used as a savory citrus seasoning — funky, bright, intensely lemony without sourness.",
		cross_cuisine_marker: "North African / Mediterranean",
		signature_ingredients: ["preserved lemon", "olive oil", "garlic", "cracked pepper"],
		example_components: ["preserved-lemon vinaigrette", "preserved-lemon aioli", "preserved-lemon yogurt", "preserved-lemon gremolata"],
		example_dishes: [
			"preserved-lemon roast chicken",
			"preserved-lemon couscous",
			"preserved-lemon hummus",
			"preserved-lemon-glazed fish",
			"preserved-lemon ricotta toast",
		],
		vibe_kind: "produce",
	},
	{
		id: "vibe_chili_crisp_on_everything",
		label: "chili-crisp-on-everything",
		description: "Lao Gan Ma-style fried chili oil with crispy garlic, fermented bean, and Sichuan peppercorn — savory crunch + heat that travels.",
		cross_cuisine_marker: "Modern American / Chinese",
		signature_ingredients: ["chili oil", "fried garlic", "Sichuan peppercorn", "fermented soybean", "crispy shallot"],
		example_components: ["chili crisp aioli", "chili crisp butter", "chili crisp vinaigrette"],
		example_dishes: [
			"chili crisp eggs",
			"chili crisp ice cream",
			"chili crisp dumplings",
			"chili crisp cacio e pepe",
			"chili crisp avocado toast",
		],
		vibe_kind: "sauce",
	},
	{
		id: "vibe_smoky_citrus",
		label: "smoky-citrus",
		description: "Charred or smoked element + bright citrus — mezcal, smoked paprika, grilled lemon. The mood of a great taco bar or wood-grilled fish night.",
		cross_cuisine_marker: null,
		signature_ingredients: ["smoked paprika", "lime", "grilled lemon", "mezcal", "chipotle"],
		example_components: ["smoky-lime crema", "smoked-citrus dressing", "mezcal-lime salt"],
		example_dishes: [
			"mezcal-grilled vegetables",
			"smoky-lime tacos",
			"grilled-citrus chicken",
			"smoked paprika shrimp with lemon",
		],
		vibe_kind: "general",
	},
	{
		id: "vibe_herby_creamy_acid",
		label: "herby-creamy-acid",
		description: "Tangy dairy + green herbs + lemon + raw garlic. Yogurt or labneh forms the body; the herb amount is always more than you think.",
		cross_cuisine_marker: "Mediterranean / Levantine",
		signature_ingredients: ["yogurt or labneh", "fresh herbs (parsley/dill/mint/basil)", "lemon", "garlic", "olive oil"],
		example_components: ["green goddess", "herb yogurt", "herbed labneh", "ranch dressing (modern)"],
		example_dishes: [
			"herb-yogurt grilled vegetables",
			"green-goddess salad",
			"herbed labneh toast",
			"yogurt-herb chicken",
		],
		vibe_kind: "sauce",
	},
	{
		id: "vibe_umami_acid_heat",
		label: "umami-acid-heat",
		description: "The Pan-Asian dressing trinity: fish sauce or soy + rice vinegar or lime + chili + ginger or garlic. Universal solvent for slaws, grain bowls, dumplings.",
		cross_cuisine_marker: "Pan-Asian / Modern American",
		signature_ingredients: ["fish sauce or soy sauce", "rice vinegar or lime", "chili", "ginger", "garlic"],
		example_components: ["nuoc cham", "chili-soy dipping", "garlic-soy", "spicy ponzu"],
		example_dishes: [
			"nuoc-cham slaw",
			"sticky rice with spicy soy",
			"crispy noodle salad",
			"fish-sauce wings",
		],
		vibe_kind: "sauce",
	},
	{
		id: "vibe_char_lime_cilantro",
		label: "char-lime-cilantro",
		description: "Fire-charred element + lime + cilantro + raw white onion — the Mexican brightness gesture.",
		cross_cuisine_marker: "Mexican-adjacent",
		signature_ingredients: ["charred element", "lime", "cilantro", "white onion", "salt"],
		example_components: ["pico de gallo", "salsa verde", "lime crema", "charred-tomatillo salsa"],
		example_dishes: [
			"charred-corn salad",
			"tacos al carbón",
			"charred-tomatillo salsa with chips",
			"lime-cilantro rice",
		],
		vibe_kind: "produce",
	},
	{
		id: "vibe_toasted_cumin_lemon",
		label: "toasted-cumin-lemon",
		description: "Whole cumin bloomed in oil + lemon + olive oil + garlic — Mediterranean and Indian-adjacent backbone.",
		cross_cuisine_marker: "Mediterranean-adjacent",
		signature_ingredients: ["toasted cumin", "lemon", "olive oil", "garlic", "salt"],
		example_components: ["cumin-lemon vinaigrette", "cumin oil", "lemon-cumin yogurt"],
		example_dishes: [
			"cumin-roasted carrots with lemon",
			"cumin-lemon chickpeas",
			"cumin-rubbed lamb with lemon",
		],
		vibe_kind: "spice",
	},
	{
		id: "vibe_sesame_soy_ginger",
		label: "sesame-soy-ginger",
		description: "Toasted sesame oil + soy + ginger + a touch of sugar — the universal Pan-Asian dressing that crosses Korean, Japanese, Chinese.",
		cross_cuisine_marker: "Pan-Asian-adjacent",
		signature_ingredients: ["toasted sesame oil", "soy sauce", "ginger", "rice vinegar", "scallion"],
		example_components: ["sesame-soy dressing", "ginger-scallion oil", "sesame ponzu"],
		example_dishes: [
			"sesame-soy noodle salad",
			"ginger-scallion chicken",
			"sesame-dressed greens",
			"smashed cucumber salad",
		],
		vibe_kind: "sauce",
	},
	{
		id: "vibe_sumac_zaatar_lemon",
		label: "sumac-zaatar-lemon",
		description: "Sumac's tart lemoniness + za'atar's herbal-thyme-sesame + actual lemon — the Levantine seasoning trio that brightens flatbread, eggs, salads.",
		cross_cuisine_marker: "Levantine",
		signature_ingredients: ["sumac", "za'atar", "lemon", "olive oil"],
		example_components: ["sumac-onion topping", "za'atar oil", "sumac-lemon dressing"],
		example_dishes: [
			"za'atar flatbread",
			"sumac-onion salad",
			"za'atar eggs",
			"fattoush",
		],
		vibe_kind: "spice",
	},
	{
		id: "vibe_tamarind_jaggery_chili",
		label: "tamarind-jaggery-chili",
		description: "Sour tamarind + earthy palm-sugar jaggery + dried red chili — the Indian-Southeast Asian sweet-sour-hot axis.",
		cross_cuisine_marker: "Indian-Southeast Asian",
		signature_ingredients: ["tamarind", "jaggery or palm sugar", "dried red chili", "cumin", "salt"],
		example_components: ["tamarind chutney", "tamarind-chili sauce", "imli"],
		example_dishes: [
			"pad thai sauce",
			"tamarind chutney for samosas",
			"tamarind-glazed eggplant",
			"tamarind-chili shrimp",
		],
		vibe_kind: "sauce",
	},
	{
		id: "vibe_fennel_orange_anise",
		label: "fennel-orange-anise",
		description: "Anise-forward gestures: fennel bulb + fennel pollen + orange + tarragon or pernod. Mediterranean-French elegance, light and aromatic.",
		cross_cuisine_marker: "Mediterranean-French",
		signature_ingredients: ["fennel", "orange", "tarragon", "pernod or anise seed", "olive oil"],
		example_components: ["fennel-orange salad", "anise-orange vinaigrette"],
		example_dishes: [
			"shaved fennel-orange salad",
			"fennel-crusted pork",
			"orange-anise braised short rib",
			"pernod cream sauce for fish",
		],
		vibe_kind: "produce",
	},
	{
		id: "vibe_rose_cardamom_pistachio",
		label: "rose-cardamom-pistachio",
		description: "The Persian / South-Asian dessert mood — floral rose, perfumed green cardamom, ground pistachio. Lives in baklava, kulfi, cakes, ice cream, syrups.",
		cross_cuisine_marker: "Persian / South-Asian dessert",
		signature_ingredients: ["rose water", "green cardamom", "pistachio", "saffron"],
		example_components: ["rose syrup", "cardamom cream", "pistachio dust"],
		example_dishes: [
			"rose-cardamom kulfi",
			"pistachio baklava",
			"rosewater rice pudding",
			"cardamom-pistachio cake",
		],
		vibe_kind: "general",
	},
	{
		id: "vibe_saffron_yogurt_lemon",
		label: "saffron-yogurt-lemon",
		description: "Bloomed saffron + thick yogurt + lemon zest — Persian and Levantine elegance. Used as a marinade, drizzle, or sauce.",
		cross_cuisine_marker: "Persian-Levantine",
		signature_ingredients: ["saffron", "yogurt or labneh", "lemon", "olive oil", "salt"],
		example_components: ["saffron yogurt", "saffron-lemon dressing", "saffron crema"],
		example_dishes: [
			"saffron-yogurt chicken",
			"saffron-lemon rice",
			"saffron-yogurt-marinated lamb",
		],
		vibe_kind: "sauce",
	},
	{
		id: "vibe_harissa_honey",
		label: "harissa-honey",
		description: "Smoky-fruity-spicy North African chili paste + honey — sweet-heat glaze that works on roasted vegetables, chicken, tofu.",
		cross_cuisine_marker: "North African-modern",
		signature_ingredients: ["harissa", "honey", "olive oil", "lemon", "garlic"],
		example_components: ["harissa-honey glaze", "harissa-honey butter", "harissa-honey vinaigrette"],
		example_dishes: [
			"harissa-honey roasted carrot",
			"harissa-honey chicken",
			"harissa-honey tofu",
			"harissa-honey roasted cauliflower",
		],
		vibe_kind: "sauce",
	},
	{
		id: "vibe_anchovy_garlic_chili",
		label: "anchovy-garlic-chili",
		description: "Italian umami spine — melted anchovy + slow-bloomed garlic + Calabrian chili flake + olive oil. Quiet but explosive.",
		cross_cuisine_marker: "Italian umami",
		signature_ingredients: ["anchovy", "garlic", "Calabrian chili flake", "olive oil"],
		example_components: ["anchovy-garlic oil", "bagna cauda", "puttanesca base"],
		example_dishes: [
			"spaghetti aglio e olio with anchovy",
			"puttanesca",
			"bagna cauda",
			"anchovy-garlic broccoli rabe",
		],
		vibe_kind: "umami",
	},
	{
		id: "vibe_browned_butter_sage_nutmeg",
		label: "browned-butter-sage-nutmeg",
		description: "Toasted milk-solid butter + crispy sage + microplane nutmeg — autumn/winter Italian comfort. Pairs with pumpkin, gnocchi, brown-meat ragus.",
		cross_cuisine_marker: "Italian-French",
		signature_ingredients: ["butter (browned)", "fresh sage", "nutmeg", "salt"],
		example_components: ["brown butter sage sauce", "brown-butter glaze"],
		example_dishes: [
			"pumpkin ravioli with brown butter sage",
			"brown butter gnocchi",
			"brown-butter butternut soup",
			"brown-butter scallops",
		],
		vibe_kind: "sauce",
	},
	{
		id: "vibe_miso_tahini_lemon",
		label: "miso-tahini-lemon",
		description: "White miso + tahini + lemon + sesame oil — cross-Pan-Asian-Levantine umami sauce. Goes on noodles, grain bowls, roasted vegetables.",
		cross_cuisine_marker: "Pan-Asian-Levantine",
		signature_ingredients: ["white miso", "tahini", "lemon", "sesame oil", "garlic"],
		example_components: ["miso-tahini sauce", "miso-tahini dressing", "miso-tahini drizzle"],
		example_dishes: [
			"miso-tahini noodles",
			"miso-tahini grilled eggplant",
			"miso-tahini broccoli",
			"miso-tahini grain bowl",
		],
		vibe_kind: "sauce",
	},
	{
		id: "vibe_pickled_everything",
		label: "pickled-everything",
		description: "Quick-pickle everything in your fridge — rice vinegar + salt + sugar + spice over carrot, daikon, red onion, cucumber, jalapeno. Brightens any rich plate.",
		cross_cuisine_marker: null,
		signature_ingredients: ["rice vinegar", "salt", "sugar", "spice (mustard seed / chili / star anise)"],
		example_components: ["banh-mi pickle (do chua)", "escabeche", "quick kimchi", "pickled red onion"],
		example_dishes: [
			"banh mi pickle plate",
			"escabeche tacos",
			"pickled-onion grain bowl",
			"quick-kimchi rice",
		],
		vibe_kind: "method",
	},
	{
		id: "vibe_labneh_with_everything",
		label: "labneh-with-everything",
		description: "Strained yogurt cheese + great olive oil + crunch (dukkah / za'atar / seeds) — a base layer for vegetables, grilled meats, sweet desserts.",
		cross_cuisine_marker: "Levantine",
		signature_ingredients: ["labneh", "olive oil", "crunch (dukkah, za'atar, sesame, sumac)", "salt"],
		example_components: ["herbed labneh", "labneh-and-dukkah base", "whipped labneh"],
		example_dishes: [
			"labneh tartine with za'atar",
			"herbed labneh dip",
			"labneh ice cream",
			"labneh with roasted carrots",
		],
		vibe_kind: "sauce",
	},
	{
		id: "vibe_calabrian_chili_honey",
		label: "calabrian-chili-honey",
		description: "Brined Calabrian chili + honey — fruity-fiery-sweet Italian gesture, lives on pizza, fried chicken, ricotta toast.",
		cross_cuisine_marker: "Italian-modern",
		signature_ingredients: ["Calabrian chili", "honey", "olive oil"],
		example_components: ["hot honey", "Calabrian-chili butter"],
		example_dishes: [
			"hot-honey pizza",
			"hot-honey fried chicken",
			"Calabrian-chili-ricotta toast",
		],
		vibe_kind: "sauce",
	},
	{
		id: "vibe_charred_alliums",
		label: "charred-alliums",
		description: "Black-charred scallion, leek, or onion blended into oil or sauce — smoky-sweet-funky depth that goes on everything from steak to dip.",
		cross_cuisine_marker: null,
		signature_ingredients: ["scallion", "leek", "onion", "neutral oil or olive oil", "salt"],
		example_components: ["charred-scallion oil", "burnt-onion butter", "charred-leek vinaigrette"],
		example_dishes: [
			"charred-scallion noodles",
			"burnt-onion dip",
			"charred-leek and ricotta toast",
		],
		vibe_kind: "produce",
	},
];
